### ISSUE TITLE
toogleMenu is not Working in UIViewController 

### ISSUE THREAD

**Issue by vishal91** [romaonthego/REMenu#85]
I am trying to use REMenu in UIViewController with Segue . 

I am UINavigationController set to UIIViewController . 

I am getting this error 

-[UINavigationController toggleMenu]: unrecognized selector sent to instance 0xa13aa80
2014-07-10 15:42:07.708 Noise[3372:607] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UINavigationController toggleMenu]: unrecognized selector sent to instance 0xa13aa80'

**Comment by Lenord2** [comment]
I am facing the above issue 3 days onwards. Still I am not getting the solution. Please help me out from this issue

**Comment by chlebta** [comment]
I got same issue And I sloved it by : 
First : Implementing the ToggleMenu
Then : instead of  using **target:self.navigationControler** I used **target:self**  when adding the MenuBarButtonItem : 
self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"Menu" style:UIBarButtonItemStyleBordered target:self action:@selector(toggleMenu)]; )
